In [2]:
import numpy as np
print('numpy version:',np.__version__)


numpy version: 1.18.1


In [4]:
# Numpy es una libreria para trabajar con vectores multidimensionales
import numpy as np 
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
b=np.array([[3,4],[7,8]],dtype=np.complex64) # dtype devuelve el tipo de los valores contenidos en el vector.
print(b)

[[3.+0.j 4.+0.j]
 [7.+0.j 8.+0.j]]


In [3]:
c = np.zeros([4,5]) # El método zeros ayuada a inicializar los valores del vector en 0
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
 d =np.zeros_like(b) # zeros_like es un método para copiar tipos y dimensiones
print(d)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]


In [13]:
e=np.empty((2,3)) # empty() muestra los valores que existian en memoria
print(e)
f =np.eye(6) # El método eye() devuelve una diagonal de 1 y los demás valores en cero
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [14]:
g=np.diag(range(7)) # diag es un método que te devuelve los valores del range en diagonal y los demas valores quedan en 0
print(g)

[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 4 0 0]
 [0 0 0 0 0 5 0]
 [0 0 0 0 0 0 6]]


In [17]:
h=np.arange(6) #arange recorre el vector con el valor dado secuencias
print(h)

[0 1 2 3 4 5]


In [22]:
np.tile(np.array([[4,6],[8,8]]),(2,3))

array([[4, 6, 4, 6, 4, 6],
       [8, 8, 8, 8, 8, 8],
       [4, 6, 4, 6, 4, 6],
       [8, 8, 8, 8, 8, 8]])

In [23]:
# Támbien es posible recurrir a generadores como este:
vector1=np.array([[10*j+i for i in range(5)] for j in range(7)])
print(vector1)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]
 [60 61 62 63 64]]


In [4]:
import numpy as np
h = np.linspace(0,15,5) # El método linspace nos permite poner espaciados en el vector
print(h)
print(h[:, np.newaxis]) # El método newaxis nos ayuda a convertir un vector fila en columna

[ 0.    3.75  7.5  11.25 15.  ]
[[ 0.  ]
 [ 3.75]
 [ 7.5 ]
 [11.25]
 [15.  ]]


In [3]:
import numpy as np
x, y = np.mgrid[0:4,1:5] #La función mgrid() el usuario determina completamente las líneas de cuadrícula horizontales y verticales
print(x)
print("----")
print(y)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
----
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [9]:
import numpy as np
from scipy import sparse 
x =np.random.random((5,6)) # Devuelve un número aleatorio entre 0.0 y 1.0:
x[x<0.85]=0
print(x)
x_csr = sparse.csr_matrix(x)
print(x_csr)
print("-------")
print(x_csr.toarray())

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.98291935 0.         0.         0.         0.        ]
 [0.         0.         0.         0.95328571 0.         0.        ]
 [0.         0.         0.         0.         0.         0.9955764 ]]
  (2, 1)	0.9829193522299748
  (3, 3)	0.9532857140569865
  (4, 5)	0.9955764044303157
-------
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.98291935 0.         0.         0.         0.        ]
 [0.         0.         0.         0.95328571 0.         0.        ]
 [0.         0.         0.         0.         0.         0.9955764 ]]


In [24]:
import numpy as np
np.random.seed(23) # método se usa para inicializar el generador de números aleatorios.
np.random.rand(3,3)

array([[0.51729788, 0.9469626 , 0.76545976],
       [0.28239584, 0.22104536, 0.68622209],
       [0.1671392 , 0.39244247, 0.61805235]])

In [26]:
import numpy as np
np.random.randn(3,3)

array([[ 2.22599652,  1.20689203,  0.67310693],
       [ 1.18175352, -1.28335478,  0.2301713 ],
       [ 0.03779385, -1.61931338, -0.40506414]])

In [27]:
import numpy as np
a = np.array([1.2,2.3,4.5])
b = a.astype(int) # El método astype() nos permite redondear el número
print(b)

[1 2 4]


In [30]:
import numpy as np
b = np.array([2.3,2.6,5.7,3.4])
c = np.around(b) # Esta función matemática ayuda al usuario a redondear de manera uniforme los elementos de la matriz al número dado de decimales.
print(c)
d = np.around(b).astype(int) # Nos devuelve un número entero
print("----------")
print(d)

[2. 3. 6. 3.]
----------
[2 3 6 3]


In [34]:
 from numpy import array
a = array([1.2,1.3,1.4,1.6])
b = array([2.3,2.4,2.5,2.6])
c = a*b # Multiplicamos los vectores con sus mismos valores
print(c)
d = a+b # Sumamos los vectores que contengan los mismos valores 
print(d)

[2.76 3.12 3.5  4.16]
[3.5 3.7 3.9 4.2]


In [13]:
 from numpy import array 
o = array([[1.2,1.2,1.3,1.4],
           [1.5,2.3,4.5,5.6]])
p= array([2.3,2.4,2.6,2.7])
c = o+p
print(c)
g = p.min() # Para sacar el minimo de un vector
k = o.max() # Para sacar el máximo de un vector
m = p.mean() # Promedia los valores del vector
s = o.cumsum()
print("-----------------")
print(g)
print("-----------------")
print(k)
print("-----------------")
print(p.T) # Sirve para obtener la transpuesta
print("-----------------")
print(m)
print("-----------------")
print(s)

[[3.5 3.6 3.9 4.1]
 [3.8 4.7 7.1 8.3]]
-----------------
2.3
-----------------
5.6
-----------------
[2.3 2.4 2.6 2.7]
-----------------
2.5
-----------------
[ 1.2  2.4  3.7  5.1  6.6  8.9 13.4 19. ]


In [15]:
print(p*5)
print(o+3)

[11.5 12.  13.  13.5]
[[4.2 4.2 4.3 4.4]
 [4.5 5.3 7.5 8.6]]


In [17]:
print(p*p.T)
print("-----------")
print(np.dot(o,o.T))

[5.29 5.76 6.76 7.29]
-----------
[[ 6.53 18.25]
 [18.25 59.15]]


In [23]:
# Para el cálculo del determinante y de la matriz inversa se utiliza la librería SciPy
#Ejemplo
from scipy import linalg
elem = np.array([[2,4],
                 [5,1]])
linalg.det(elem) # Para calcular la determinante del vector

-18.0

In [27]:
from scipy import linalg
elem = np.array([[2,4],
                 [5,1]])
linalg.inv(elem) # Para calculara la inversa del vector
print(elem[0,0]) # Imprimimos el primer elemento de la primera fila y primera columna
print(elem[:,0]) # Imprime la columna que se desea

2
[2 5]


In [29]:
 elem2 = np.array(elem, copy= True) # Nos permite copiar un vector con sus mismos valores
print(elem2)

[[2 4]
 [5 1]]


In [31]:
 # Librería Pandas
 # El DataFrame te permite almacenar y manipular datos tabulados en filas de observaciones y columnas de variables.
import pandas as pd
import numpy as np
variable = pd.Series([1,2,3,np.nan,4,5])
print(variable)

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    5.0
dtype: float64


In [1]:
import pandas as pd
import numpy as np
dates = pd.date_range('20200701',periods =4)
print(dates)

DatetimeIndex(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04'], dtype='datetime64[ns]', freq='D')


In [4]:
import pandas as pd
import numpy as np
fecha = pd.DataFrame(np.random.randn(4,3), index = dates, columns = list('ABC'))
print(fecha)

                   A         B         C
2020-07-01  0.875536  1.273121  1.889003
2020-07-02 -2.116504 -0.773906 -2.597189
2020-07-03  0.620152  1.810917  1.106116
2020-07-04 -1.018629 -0.835203 -0.622112


In [8]:
import pandas as pd
import numpy as np
datos2 = pd.DataFrame({
    'A':2.3,
    'B':pd.Timestamp('20200701'),
    'C':pd.Series(1,index=list(range(4)),dtype='float32'),
    'D':np.array([3]*4,dtype='int32'),
    'E':pd.Categorical(["manzana","pera","uva","frutilla"]),
    'F':'Frutas'
})
print(datos2)
print("---------")
datos2.index
print("---------")
datos2.columns
print("---------")
datos2.values
datos2.describe()

     A          B    C  D         E       F
0  2.3 2020-07-01  1.0  3   manzana  Frutas
1  2.3 2020-07-01  1.0  3      pera  Frutas
2  2.3 2020-07-01  1.0  3       uva  Frutas
3  2.3 2020-07-01  1.0  3  frutilla  Frutas
---------
---------
---------


A    C    D
count  4.0  4.0  4.0
mean   2.3  1.0  3.0
std    0.0  0.0  0.0
min    2.3  1.0  3.0
25%    2.3  1.0  3.0
50%    2.3  1.0  3.0
75%    2.3  1.0  3.0
max    2.3  1.0  3.0

In [9]:
import pandas as pd
import numpy as np
datos2.T # Transpuesta de un vector

0                    1                    2  \
A                  2.3                  2.3                  2.3   
B  2020-07-01 00:00:00  2020-07-01 00:00:00  2020-07-01 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   
E              manzana                 pera                  uva   
F               Frutas               Frutas               Frutas   

                     3  
A                  2.3  
B  2020-07-01 00:00:00  
C                    1  
D                    3  
E             frutilla  
F               Frutas

In [11]:
import pandas as pd
import numpy as np
datos2.sort_index(axis = 1, ascending = False) # Ordenar los valores de un vector

F         E  D    C          B    A
0  Frutas   manzana  3  1.0 2020-07-01  2.3
1  Frutas      pera  3  1.0 2020-07-01  2.3
2  Frutas       uva  3  1.0 2020-07-01  2.3
3  Frutas  frutilla  3  1.0 2020-07-01  2.3

In [12]:
import pandas as pd
import numpy as np
datos2.head()

A          B    C  D         E       F
0  2.3 2020-07-01  1.0  3   manzana  Frutas
1  2.3 2020-07-01  1.0  3      pera  Frutas
2  2.3 2020-07-01  1.0  3       uva  Frutas
3  2.3 2020-07-01  1.0  3  frutilla  Frutas

In [13]:
import pandas as pd
import numpy as np
datos2.tail(3)

A          B    C  D         E       F
1  2.3 2020-07-01  1.0  3      pera  Frutas
2  2.3 2020-07-01  1.0  3       uva  Frutas
3  2.3 2020-07-01  1.0  3  frutilla  Frutas

In [14]:
datos2['E'] # Acceder a los datos de un vector

0     manzana
1        pera
2         uva
3    frutilla
Name: E, dtype: category
Categories (4, object): [frutilla, manzana, pera, uva]

In [16]:
datos2[0:2] # Te devuelve el numero de de filas desde un punto a otro punto 

A          B    C  D        E       F
0  2.3 2020-07-01  1.0  3  manzana  Frutas
1  2.3 2020-07-01  1.0  3     pera  Frutas

In [19]:
datos2.loc[:,['A','B']] # Te permite elegir la columna que deseas que se vea o visualize

A          B
0  2.3 2020-07-01
1  2.3 2020-07-01
2  2.3 2020-07-01
3  2.3 2020-07-01

In [22]:
datos2[datos2.C > 0] #Podemos utilizar simbolos para obtener un resultado

A          B    C  D         E       F
0  2.3 2020-07-01  1.0  3   manzana  Frutas
1  2.3 2020-07-01  1.0  3      pera  Frutas
2  2.3 2020-07-01  1.0  3       uva  Frutas
3  2.3 2020-07-01  1.0  3  frutilla  Frutas

In [25]:
# Pandas nos proporciona la función join() que nos permiten cruzar dos DataFrames para este propósito.
import pandas as pd
import numpy as np

a = pd.DataFrame({'Nombres': ['Roger', 'Elias'], 'Apellidos':[5,7]})
b = pd.DataFrame({'Nombres': ['Roger', 'Elias'], 'Apellidos':[2,4]})
pd.merge(a,b, on = 'Nombres') # Se puede unir los vectores cuando tienen la misma llave y el mismo valor

Nombres  Apellidos_x  Apellidos_y
0   Roger            5            2
1   Elias            7            4

In [30]:
import numpy as np 
import pandas as pd

datos2 = pd.DataFrame({
    'A':['uno','dos','tres','cuatro','uno','dos','tres','cuatro'],
    'B':['tierra','aire','agua','fuego','tierra','aire','agua','fuego'],
    'C':np.random.randn(8),
    'D':np.random.randn(8)})
print(datos2)
datos2.groupby('B').sum()

        A       B         C         D
0     uno  tierra  1.856394 -0.157814
1     dos    aire  0.982568  0.039165
2    tres    agua  1.376643  0.541011
3  cuatro   fuego -0.821444  0.279711
4     uno  tierra -0.115951  0.873607
5     dos    aire  0.305954  1.067541
6    tres    agua -1.585447  0.644785
7  cuatro   fuego -0.805825  1.526407


C         D
B                         
agua   -0.208804  1.185796
aire    1.288523  1.106707
fuego  -1.627269  1.806118
tierra  1.740443  0.715793

In [31]:

datos2.groupby('B').sum()

C         D
B                         
agua   -0.208804  1.185796
aire    1.288523  1.106707
fuego  -1.627269  1.806118
tierra  1.740443  0.715793