<a href="https://colab.research.google.com/github/elias9314/Actividades/blob/master/pythorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'1.6.0+cu101'

In [3]:
# la funcion ones sirve para llenar una matriz con valores de uno
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [4]:
tenso_p = torch.ones(4,4)
print(tenso_p)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# la funcion Tensor nos permite llenar la matriz con datos aleatorios
tenso_b = torch.Tensor(4,4)
tenso_b

tensor([[2.1097e-36, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 6.4460e-44, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28],
        [3.8016e-39, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
# una de las funciones que nos permite dar un limite que podemos dar a los datos en .uniform_
tensor_b = torch.Tensor(4,4)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[2.1100e-36, 0.0000e+00, 2.2421e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 4.8222e+30, 1.8057e+28],
        [7.9050e+31, 5.5515e-08, 4.5081e+16, 6.6018e-10],
        [1.6615e-07, 1.3032e-43, 0.0000e+00, 0.0000e+00]])


tensor([[0.4310, 0.2018, 0.5216, 0.6928],
        [0.9653, 0.8408, 0.3197, 0.1105],
        [0.1483, 0.9966, 0.5180, 0.1539],
        [0.5461, 0.8939, 0.5416, 0.4228]])

In [10]:
#para generar datos aleatorios utilizamos el metodo .rand
tensor_c = torch.rand(4,4)
tensor_c

tensor([[0.2663, 0.2983, 0.8996, 0.1110],
        [0.6411, 0.9792, 0.8877, 0.7790],
        [0.2989, 0.2461, 0.5122, 0.0625],
        [0.8821, 0.4996, 0.7103, 0.6089]])

In [11]:
# Podemos realizar operaciones siempre y cuando las matematicas sean correctas
result = tensor_b + tensor_c
result

tensor([[0.6974, 0.5001, 1.4212, 0.8038],
        [1.6064, 1.8200, 1.2074, 0.8895],
        [0.4472, 1.2427, 1.0302, 0.2163],
        [1.4281, 1.3935, 1.2519, 1.0317]])

In [12]:
resultado = tensor_b - tensor_c
resultado

tensor([[ 0.1647, -0.0966, -0.3780,  0.5818],
        [ 0.3243, -0.1384, -0.5679, -0.6685],
        [-0.1506,  0.7504,  0.0058,  0.0914],
        [-0.3360,  0.3942, -0.1687, -0.1861]])

In [13]:
# el metodo .shape nos da las dimensiones de nuestro tensor
resultado.shape

torch.Size([4, 4])

In [14]:
# .view tranforma el tensor en caso de ser necesario
resultadotensor = resultado.view(1,16)
print(resultadotensor)

tensor([[ 0.1647, -0.0966, -0.3780,  0.5818,  0.3243, -0.1384, -0.5679, -0.6685,
         -0.1506,  0.7504,  0.0058,  0.0914, -0.3360,  0.3942, -0.1687, -0.1861]])


In [15]:
resultadotensor = resultado.view(1,16)
resultadotensor

tensor([[ 0.1647, -0.0966, -0.3780,  0.5818,  0.3243, -0.1384, -0.5679, -0.6685,
         -0.1506,  0.7504,  0.0058,  0.0914, -0.3360,  0.3942, -0.1687, -0.1861]])

In [16]:
# el metodo .tensor nos permite agregar datos en una matriz en base a lo que el autor lo desee o necesite
tensor_d = torch.tensor([[1.0,1.1,1.2,1.3],[1.4,1.5,1.6,1.7],[0.1,0.2,0.3,0.4],[2.1,2.2,2.3,2.4]])
tensor_d

tensor([[1.0000, 1.1000, 1.2000, 1.3000],
        [1.4000, 1.5000, 1.6000, 1.7000],
        [0.1000, 0.2000, 0.3000, 0.4000],
        [2.1000, 2.2000, 2.3000, 2.4000]])

In [20]:
# para llamar un dato especifico, se lo llama en base a su ubicacion dentro de la matriz
print(tensor_d[3][3])

tensor(2.4000)


In [21]:
# para cambiar el dato de una matriz se lo hace de la siguiente manera:
tensor_d [3][3] = 0.45
print(tensor_d)

tensor([[1.0000, 1.1000, 1.2000, 1.3000],
        [1.4000, 1.5000, 1.6000, 1.7000],
        [0.1000, 0.2000, 0.3000, 0.4000],
        [2.1000, 2.2000, 2.3000, 0.4500]])


In [22]:
# .storage() nos permite guardar despecificamente en un espacio de memoria
tensor_d.storage()

 1.0
 1.100000023841858
 1.2000000476837158
 1.2999999523162842
 1.399999976158142
 1.5
 1.600000023841858
 1.7000000476837158
 0.10000000149011612
 0.20000000298023224
 0.30000001192092896
 0.4000000059604645
 2.0999999046325684
 2.200000047683716
 2.299999952316284
 0.44999998807907104
[torch.FloatStorage of size 16]

In [26]:
# el  metodo .stride, se refiere a como se puede mover una serie de datos a otra en base a las dimensiones del tensor o matriz
tensor_d, tensor_d.stride()

(tensor([[1.0000, 1.1000, 1.2000, 1.3000],
         [1.4000, 1.5000, 1.6000, 1.7000],
         [0.1000, 0.2000, 0.3000, 0.4000],
         [2.1000, 2.2000, 2.3000, 0.4500]]), (4, 1))

In [28]:
# para crear una transpuesta utilizamos el .t
transpuesta = tensor_d.t()
transpuesta, transpuesta.stride()

(tensor([[1.0000, 1.4000, 0.1000, 2.1000],
         [1.1000, 1.5000, 0.2000, 2.2000],
         [1.2000, 1.6000, 0.3000, 2.3000],
         [1.3000, 1.7000, 0.4000, 0.4500]]), (1, 4))

In [30]:
# .unsqueeze agrega una dimension a un tensor en caso de ser necesario
tensor_x = torch.tensor([1,2,3,4,5,6,7,8,9])
print(tensor_x), torch.unsqueeze(tensor_x,1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


(None, tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]))

In [31]:
#biblioteca para el procesamiento de datoa en ml, principalmente numericos
import numpy as np


In [32]:
numpayArray = np.random.randn(4,4)
torch.from_numpy(numpayArray)

tensor([[ 0.1846,  1.0085,  0.4514,  1.1427],
        [-0.1354, -1.7204,  0.3051,  0.4348],
        [-1.2806, -0.0801, -1.8361,  1.2286],
        [ 0.2828, -0.4687,  2.2142,  2.4225]], dtype=torch.float64)